#!/bin/bash
#tinylog
#rich@smalldefeats.com

#Settings!
source 'tinysettings.cfg'

#Functions!
function init {
	if [ -d $TINY_PATH ]; then
		echo $TINY_PATH already exists.
	else
		mkdir $TINY_PATH
	fi
}

function new {
	YEAR=$(date +"%Y")
	MONTH=$(date +"%B")
	NEW_PATH=$TINY_PATH/$YEAR/$MONTH
	NEW_NAME=$(date +"%d_%k_%m_%S")
	
	if [ -d $NEW_PATH ]; then
		$TEXT_EDITOR $NEW_PATH/$NEW_NAME.txt
	else
		mkdir -p $NEW_PATH
		$TEXT_EDITOR $NEW_PATH/$NEW_NAME.txt
	fi	
}

function open {
	$TEXT_EDITOR $PATH_TO_OPEN
}

#Arguments!
case "$1" in
	"init") init
	;;
	"new")	new
	;;
	"") tree $TINY_PATH
	;;
	"open") PATH_TO_OPEN=$TINY_PATH/$2
			open
	;;
esac